#ifndef CGAL_GLFW_BV_SETTINGS_H
#define CGAL_GLFW_BV_SETTINGS_H

/*************OPENGL GLFW PARAMS*************/

#ifndef CGAL_GLFW_OPENGL_MAJOR_CORE
#define CGAL_GLFW_OPENGL_MAJOR_CORE 4
#endif

#ifndef CGAL_GLFW_OPENGL_MINOR_CORE
#define CGAL_GLFW_OPENGL_MINOR_CORE 3
#endif

/*************GLFW WINDOW PARAMS*************/

#ifndef CGAL_GLFW_DEFAULT_WINDOW_WIDTH
#define CGAL_GLFW_DEFAULT_WINDOW_WIDTH 500
#endif

#ifndef CGAL_GLFW_DEFAULT_WINDOW_HEIGHT
#define CGAL_GLFW_DEFAULT_WINDOW_HEIGHT 450
#endif

#ifndef CGAL_GLFW_WINDOW_SAMPLES
#define CGAL_GLFW_WINDOW_SAMPLES 1
#endif

/*************GLFW SCENE PARAMS*************/

#ifndef CGAL_GLFW_SIZE_RAYS
#define CGAL_GLFW_SIZE_RAYS 3.1f
#endif

#ifndef CGAL_GLFW_SIZE_LINES
#define CGAL_GLFW_SIZE_LINES 3.1f
#endif

#ifndef CGAL_GLFW_NORMALS_MONO_COLOR
#define CGAL_GLFW_NORMALS_MONO_COLOR { 220, 20, 20 }
#endif

#ifndef CGAL_GLFW_LIGHT_POSITION
#define CGAL_GLFW_LIGHT_POSITION { 0.0f, 0.0f, 0.0f, 0.0f }
#endif

#ifndef CGAL_GLFW_AMBIENT_COLOR
#define CGAL_GLFW_AMBIENT_COLOR { 0.6f, 0.5f, 0.5f, 0.5f }
#endif

#ifndef CGAL_GLFW_DIFFUSE_COLOR
#define CGAL_GLFW_DIFFUSE_COLOR { 0.9f, 0.9f, 0.9f, 0.9f }
#endif

#ifndef CGAL_GLFW_SPECULAR_COLOR
#define CGAL_GLFW_SPECULAR_COLOR { 0.0f, 0.0f, 0.0f, 1.0f }
#endif

#ifndef CGAL_GLFW_SHININESS
#define CGAL_GLFW_SHININESS 1.0f
#endif

/************GLFW CAMERA PARAMS*************/

#ifndef CGAL_GLFW_CAMERA_TRANSLATION_SPEED
#define CGAL_GLFW_CAMERA_TRANSLATION_SPEED 1.f
#endif

#ifndef CGAL_GLFW_CAMERA_ROTATION_SPEED
#define CGAL_GLFW_CAMERA_ROTATION_SPEED 270.f
#endif

#ifndef CGAL_GLFW_CAMERA_RADIUS
#define CGAL_GLFW_CAMERA_RADIUS 5.f
#endif

#ifndef CGAL_GLFW_CAMERA_FOV
#define CGAL_GLFW_CAMERA_FOV 45.f
#endif

#ifndef CGAL_GLFW_CAMERA_TRANSLATION_SMOOTHNESS
#define CGAL_GLFW_CAMERA_TRANSLATION_SMOOTHNESS 0.25f
#endif

#ifndef CGAL_GLFW_CAMERA_ROTATION_SMOOTHNESS
#define CGAL_GLFW_CAMERA_ROTATION_SMOOTHNESS 0.25f
#endif

#ifndef CGAL_GLFW_CAMERA_ZOOM_SMOOTHNESS
#define CGAL_GLFW_CAMERA_ZOOM_SMOOTHNESS 0.1f
#endif

#ifndef CGAL_GLFW_CAMERA_DRAG_TRANSLATION_SPEED
#define CGAL_GLFW_CAMERA_DRAG_TRANSLATION_SPEED 0.001f
#endif

#ifndef CGAL_GLFW_CAMERA_ZOOM_SPEED
#define CGAL_GLFW_CAMERA_ZOOM_SPEED 0.01f
#endif

/*********GLFW CLIPPING PLANE PARAMS********/

#ifndef CGAL_GLFW_CLIPPING_PLANE_RENDERING_TRANSPARENCY
#define CGAL_GLFW_CLIPPING_PLANE_RENDERING_TRANSPARENCY 0.5f
#endif

#ifndef CGAL_GLFW_CLIPPING_PLANE_TRANSLATION_SPEED
#define CGAL_GLFW_CLIPPING_PLANE_TRANSLATION_SPEED 0.25f
#endif

#ifndef CGAL_GLFW_CLIPPING_PLANE_NORMAL_TRANSLATION_SPEED
#define CGAL_GLFW_CLIPPING_PLANE_NORMAL_TRANSLATION_SPEED 0.25f
#endif

#ifndef CGAL_GLFW_CLIPPING_PLANE_DRAG_TRANSLATION_SPEED
#define CGAL_GLFW_CLIPPING_PLANE_DRAG_TRANSLATION_SPEED 1.0f
#endif

#ifndef CGAL_GLFW_CLIPPING_PLANE_ROTATION_SPEED
#define CGAL_GLFW_CLIPPING_PLANE_ROTATION_SPEED 270.f
#endif

#ifndef CGAL_GLFW_CLIPPING_PLANE_TRANSLATION_SMOOTH_RATE
#define CGAL_GLFW_CLIPPING_PLANE_TRANSLATION_SMOOTH_RATE 15.0f
#endif

#ifndef CGAL_GLFW_CLIPPING_PLANE_ROTATION_SMOOTH_RATE
#define CGAL_GLFW_CLIPPING_PLANE_ROTATION_SMOOTH_RATE 0.35f
#endif

#endif // CGAL_GLFW_BV_SETTINGS_H
